"""add application details

Revision ID: f8e413352aa2
Revises: 
Create Date: 2026-09-12 21:06:15.697221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8e413352aa2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('application')
    op.add_column('applications', sa.Column('date_applied', sa.DateTime(), nullable=True))
    op.add_column('applications', sa.Column('interview_date', sa.DateTime(), nullable=True))
    op.add_column('applications', sa.Column('notes', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'notes')
    op.drop_column('applications', 'interview_date')
    op.drop_column('applications', 'date_applied')
    op.create_table('application',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('company', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('position', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('application_pkey'))
    )
    # ### end Alembic commands ###
